// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN1_SK82RHAQrqNMAaobMvEY2UhA2tF2A',
    appId: '1:246705111271:web:e86ec08bf69eef864be242',
    messagingSenderId: '246705111271',
    projectId: 'pushnotification-122f7',
    authDomain: 'pushnotification-122f7.firebaseapp.com',
    storageBucket: 'pushnotification-122f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgOuB4TOKZZgNX2YGqYHjPHEjlLkuxzSg',
    appId: '1:246705111271:android:39c8ede7c781ebc14be242',
    messagingSenderId: '246705111271',
    projectId: 'pushnotification-122f7',
    storageBucket: 'pushnotification-122f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS_H-cU5nUQeDURiUVmqa4x10h9FqASkk',
    appId: '1:246705111271:ios:b4d6db84f1fff0e94be242',
    messagingSenderId: '246705111271',
    projectId: 'pushnotification-122f7',
    storageBucket: 'pushnotification-122f7.appspot.com',
    iosBundleId: 'com.TPP.onedaytrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS_H-cU5nUQeDURiUVmqa4x10h9FqASkk',
    appId: '1:246705111271:ios:b4d6db84f1fff0e94be242',
    messagingSenderId: '246705111271',
    projectId: 'pushnotification-122f7',
    storageBucket: 'pushnotification-122f7.appspot.com',
    iosBundleId: 'com.TPP.onedaytrip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN1_SK82RHAQrqNMAaobMvEY2UhA2tF2A',
    appId: '1:246705111271:web:5272764c1f85591d4be242',
    messagingSenderId: '246705111271',
    projectId: 'pushnotification-122f7',
    authDomain: 'pushnotification-122f7.firebaseapp.com',
    storageBucket: 'pushnotification-122f7.appspot.com',
  );
}
